name: Deploy

on:
  push:
    branches:
      - cloudflare-integration # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build webpack
        env:
          PROJECT_ACCESS_KEY_NEXT: ${{ secrets.PROJECTACCESSKEY }}
          PROJECT_ACCESS_KEY_PROD: ${{ secrets.PROJECTACCESSKEY_PROD }}
          WAAS_CONFIG_KEY: ${{ secrets.WAASCONFIGKEY }}
          WALLET_CONNECT_ID: ${{ secrets.WALLETCONNECTID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLECLIENTID }}
          APPLE_CLIENT_ID: ${{ secrets.APPLECLIENTID }}
        run: npm run build
      - name: Setup Pages
        uses: actions/setup-node@v2
        with:
          branch: cloudflare-integration
          folder: build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
